name: Android CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GPR_KEY: ${{ secrets.GPR_KEY }}
      FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
      FIREBASE_AUTH_TOKEN: ${{ secrets.FIREBASE_AUTH_TOKEN }}
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'  
          java-version: '11'

      - name: Build Debug APK
        run: ./gradlew assembleDebug -Pgpr.key=$GPR_KEY

      - name: Run Lint
        run: ./gradlew lint

      - name: Run Detekt (Static Code Analysis)
        run: ./gradlew detekt

      - name: Run Dependency Check (Security Scan)
        run: ./gradlew dependencyCheckAnalyze

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ env.FIREBASE_APP_ID }}
          token: ${{ env.FIREBASE_AUTH_TOKEN }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
